# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(576, 495)
        self.gridLayout = QtWidgets.QGridLayout(SettingsWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.minimizeOnRecord = QtWidgets.QCheckBox(SettingsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimizeOnRecord.sizePolicy().hasHeightForWidth())
        self.minimizeOnRecord.setSizePolicy(sizePolicy)
        self.minimizeOnRecord.setObjectName("minimizeOnRecord")
        self.verticalLayout.addWidget(self.minimizeOnRecord)
        self.hideWhenClosed = QtWidgets.QCheckBox(SettingsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hideWhenClosed.sizePolicy().hasHeightForWidth())
        self.hideWhenClosed.setSizePolicy(sizePolicy)
        self.hideWhenClosed.setMaximumSize(QtCore.QSize(168, 16777215))
        self.hideWhenClosed.setObjectName("hideWhenClosed")
        self.verticalLayout.addWidget(self.hideWhenClosed, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Form"))
        self.minimizeOnRecord.setText(_translate("SettingsWindow", "Minimize On Recording"))
        self.hideWhenClosed.setText(_translate("SettingsWindow", "Hide to tray when closing"))
